[package]
name = "gitvote"
description = "GitVote server"
version = "1.3.0"
license = "Apache-2.0"
edition = "2021"

[dependencies]

[dev-dependencies]
http-body = "1.0.1"
hyper = "1.4.1"
mockall = "0.13.0"
